/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-web-interface-0.5.0/debian/ros-groovy-web-interface/opt/ros/groovy/stacks/web_interface/launchman/srv/StartTask.srv */
#ifndef LAUNCHMAN_SERVICE_STARTTASK_H
#define LAUNCHMAN_SERVICE_STARTTASK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace launchman
{
template <class ContainerAllocator>
struct StartTaskRequest_ {
  typedef StartTaskRequest_<ContainerAllocator> Type;

  StartTaskRequest_()
  : taskid()
  , username()
  {
  }

  StartTaskRequest_(const ContainerAllocator& _alloc)
  : taskid(_alloc)
  , username(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _taskid_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  taskid;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _username_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  username;


  typedef boost::shared_ptr< ::launchman::StartTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::launchman::StartTaskRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartTaskRequest
typedef  ::launchman::StartTaskRequest_<std::allocator<void> > StartTaskRequest;

typedef boost::shared_ptr< ::launchman::StartTaskRequest> StartTaskRequestPtr;
typedef boost::shared_ptr< ::launchman::StartTaskRequest const> StartTaskRequestConstPtr;



template <class ContainerAllocator>
struct StartTaskResponse_ {
  typedef StartTaskResponse_<ContainerAllocator> Type;

  StartTaskResponse_()
  : status()
  {
  }

  StartTaskResponse_(const ContainerAllocator& _alloc)
  : status(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  status;


  typedef boost::shared_ptr< ::launchman::StartTaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::launchman::StartTaskResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartTaskResponse
typedef  ::launchman::StartTaskResponse_<std::allocator<void> > StartTaskResponse;

typedef boost::shared_ptr< ::launchman::StartTaskResponse> StartTaskResponsePtr;
typedef boost::shared_ptr< ::launchman::StartTaskResponse const> StartTaskResponseConstPtr;


struct StartTask
{

typedef StartTaskRequest Request;
typedef StartTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct StartTask
} // namespace launchman

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::launchman::StartTaskRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::launchman::StartTaskRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::launchman::StartTaskRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f90254a4a4912432fb92a8e890bdfbcd";
  }

  static const char* value(const  ::launchman::StartTaskRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf90254a4a4912432ULL;
  static const uint64_t static_value2 = 0xfb92a8e890bdfbcdULL;
};

template<class ContainerAllocator>
struct DataType< ::launchman::StartTaskRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "launchman/StartTaskRequest";
  }

  static const char* value(const  ::launchman::StartTaskRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::launchman::StartTaskRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string taskid\n\
string username\n\
\n\
";
  }

  static const char* value(const  ::launchman::StartTaskRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::launchman::StartTaskResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::launchman::StartTaskResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::launchman::StartTaskResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const  ::launchman::StartTaskResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::launchman::StartTaskResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "launchman/StartTaskResponse";
  }

  static const char* value(const  ::launchman::StartTaskResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::launchman::StartTaskResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string status\n\
\n\
\n\
";
  }

  static const char* value(const  ::launchman::StartTaskResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::launchman::StartTaskRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.taskid);
    stream.next(m.username);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartTaskRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::launchman::StartTaskResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.status);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartTaskResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<launchman::StartTask> {
  static const char* value() 
  {
    return "a7f7c2a0ff94dc94508b68c526bc0b69";
  }

  static const char* value(const launchman::StartTask&) { return value(); } 
};

template<>
struct DataType<launchman::StartTask> {
  static const char* value() 
  {
    return "launchman/StartTask";
  }

  static const char* value(const launchman::StartTask&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<launchman::StartTaskRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a7f7c2a0ff94dc94508b68c526bc0b69";
  }

  static const char* value(const launchman::StartTaskRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<launchman::StartTaskRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "launchman/StartTask";
  }

  static const char* value(const launchman::StartTaskRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<launchman::StartTaskResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a7f7c2a0ff94dc94508b68c526bc0b69";
  }

  static const char* value(const launchman::StartTaskResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<launchman::StartTaskResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "launchman/StartTask";
  }

  static const char* value(const launchman::StartTaskResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // LAUNCHMAN_SERVICE_STARTTASK_H

