(cl:defpackage launchman-srv
  (:use )
  (:export
   "STARTTASK"
   "<STARTTASK-REQUEST>"
   "STARTTASK-REQUEST"
   "<STARTTASK-RESPONSE>"
   "STARTTASK-RESPONSE"
   "LISTTASKS"
   "<LISTTASKS-REQUEST>"
   "LISTTASKS-REQUEST"
   "<LISTTASKS-RESPONSE>"
   "LISTTASKS-RESPONSE"
   "STATUSUPDATE"
   "<STATUSUPDATE-REQUEST>"
   "STATUSUPDATE-REQUEST"
   "<STATUSUPDATE-RESPONSE>"
   "STATUSUPDATE-RESPONSE"
   "STOPTASK"
   "<STOPTASK-REQUEST>"
   "STOPTASK-REQUEST"
   "<STOPTASK-RESPONSE>"
   "STOPTASK-RESPONSE"
  ))

